### ISSUE TITLE
Exception when trying to drag the slider button

### ISSUE THREAD

**Issue by MrCsabaToth** [threerings/tripleplay#51]
I reporduced this with the slider demo page. If I touch any of the three slider buttons, I receive similar exception, on Java platform (`mvn -Pjava install`):

```
Interaction failure [layer=GroupLayerGL [hashCode=2114893315, tx=affine [+1.0 +0.0 +0.0 +1.0 +0.0+0.0], hitTester=HitTester for tripleplay.ui.Slider@6718b196, iact=playn.core.Dispatcher$DelegatingInteraction@63323bb, event=Pointer.Event[time=8.02682E7, flags=normal, x=307.0, y=186.0, hit=GroupLayerGL [hashCode=2114893315, tx=affine [+1.0 +0.0 +0.0 +1.0 +0.0+0.0], hitTester=HitTester for tripleplay.ui.Slider@6718b196]]
java.lang.NoSuchMethodError: pythagoras.f.Point.<init>(Lpythagoras/f/IPoint;)V
    at tripleplay.ui.Behavior$Track$State.<init>(Behavior.java:169)
    at tripleplay.ui.Behavior$Track.createState(Behavior.java:203)
    at tripleplay.ui.Behavior$Track.onPress(Behavior.java:215)
    at tripleplay.ui.Behavior.onPointerStart(Behavior.java:332)
    at playn.core.PointerImpl$1.interact(PointerImpl.java:141)
    at playn.core.PointerImpl$1.interact(PointerImpl.java:139)
    at playn.core.Dispatcher$DelegatingInteraction.interact(Dispatcher.java:145)
    at playn.core.Dispatcher$DelegatingInteraction.interact(Dispatcher.java:110)
    at playn.core.AbstractLayer.interact(AbstractLayer.java:392)
    at playn.core.AbstractLayer.interact(AbstractLayer.java:372)
    at playn.core.Dispatcher.tryInteract(Dispatcher.java:163)
    at playn.core.Dispatcher$2.dispatch(Dispatcher.java:85)
    at playn.core.Dispatcher.dispatch(Dispatcher.java:187)
    at playn.core.PointerImpl.onPointerStart(PointerImpl.java:82)
    at playn.java.JavaPointer.onMouseDown(JavaPointer.java:26)
    at playn.java.JavaMouse.onMouseDown(JavaMouse.java:38)
    at playn.java.JavaLWJGLMouse.update(JavaLWJGLMouse.java:70)
    at playn.java.JavaPlatform.processFrame(JavaPlatform.java:363)
    at playn.java.JavaPlatform.run(JavaPlatform.java:312)
    at playn.core.PlayN.run(PlayN.java:74)
    at tripleplay.demo.TripleDemoJava.main(TripleDemoJava.java:61)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by MrCsabaToth** [comment]
There's no constructor which takes IPoint in pythagoras indeed. Since Jan 15 "Take XY wherever we took IPoint." https://github.com/samskivert/pythagoras/commit/72a35225d2f0e4f55859467c4e51a22fb4d15fde

**Comment by MrCsabaToth** [comment]
Hmmm, Point extends AbstractPoint, which implements IPoint, which extends from XY. So theoretically Point implements XY interface. So even IPoint should provide XY.

**Comment by MrCsabaToth** [comment]
I got the trunk from pythagoras, but still have this error. I have the trunk from pythagoras, playn and tripleplay too.

**Comment by MrCsabaToth** [comment]
Is it just my system?

**Comment by tomfisher** [comment]
Use the PlayN 1.9 release version which is shipped with Pythagoras 1.4.2

**Comment by MrCsabaToth** [comment]
tomfisher: that helped, I went from 1.9-SNAPSHOT (both PlayN, TriplePlay) to 1.9.

**Comment by guillerodriguez** [comment]
@samskivert Apparently this was solved, the issue should probably be closed.
